modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="xenorite"
version="3.0.0"
displayName="Xenorite"
credits="Created by TechieCrow and Chewablebliss"
displayURL="https://github.com/TechieCrow/Xenorite-v3"
authors="TechieCrow"
description='''
Xenorite is a mod for Minecraft that adds more ores to the game, these ores are either good ore evil in some way or another, giving you good or bad buffs and other interesting effects, with these ores comes items such as tools, weapons and armour just like in vanilla Minecraft but of course with those interesting effects.
'''

[[dependencies.xenorite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.xenorite]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xenorite]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

